node {    
      def app

      stage('Clone repository') {               
             
            git "https://github.com/giusephamquoclong/dns-proxmox.git"    
      }     
      stage('Build image') {         
       
            app = docker.build("longpham08081997/proxmox","./nslookup")    
       }     
     
       stage('Push image') {
           docker.withRegistry('','dockerhub'){
            app.push("latest")        
           }
        }
}